name: Homebrew Tap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/homebrew/ubuntu22.04:master

    steps:
    - name: Tap
      run: brew tap osalbahr/lilipod https://github.com/osalbahr/lilipod

    - name: Audit
      run: brew audit --strict --online lilipod

    - name: Install
      run: brew install lilipod
