# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Homebrew Tap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Homebrew
      run: eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

    - name: Test Lilipod
      run: |
        brew test-bot osalbahr/lilipod/lilipod
