name: Homebrew Tap

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Test Lilipod
      run: |
        eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
        brew tap osalbahr/lilipod https://github.com/osalbahr/lilipod
        brew test-bot osalbahr/lilipod/lilipod
